name: Build and package LEVENSHTEIN plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin-new.yml@main
    with:
      mariadb_versions: 74647 75199 75263
      test_suites: levenshtein
