name: Build and package LEVENSHTEIN plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: vuvova/mariadb-plugin-ci/.github/workflows/build-plugin-new.yml@main
    with:
      mariadb_versions: 74630
