name: Build and package LEVENSHTEIN plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@v1
    with:
      plugin_name: levenshtein
      plugin_directory: levenshtein
      build_target: levenshtein
      plugin_library: levenshtein.so
      cmake_options: -DPLUGIN_DATE_EXTRA=DYNAMIC
      test_suite: levenshtein
      run_tests: ${{ startsWith(github.ref, 'refs/tags/v') }}
